### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rkern** [poke1024/pyalign#2]
Hi!

The included `LICENSE` text is MIT, but the PyPI metadata in `setup.py` says `GPLv2`. Which is the correct license?

Thanks!

**Comment by poke1024** [comment]
It's MIT, I just fixed it (https://github.com/poke1024/pyalign/commit/8951041002f7a293618ccf8864163ed01ee042e6).

**Comment by rkern** [comment]
Thank you very much!
